import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GSAPProvider } from "@/context/GSAPContext";
import AdminStyles from "@/components/AdminStyles";
import { OverlayProvider } from "@/context/OverlayContext";
import { Theme } from "@radix-ui/themes";
import QueryProvider from "@/lib/queryclient";
import {Toaster} from 'react-hot-toast'
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="color-scheme" content="dark" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
        <Theme>
          <AdminStyles />
          <GSAPProvider>
            <OverlayProvider>
              <Providers>
              {children}
              </Providers>
            <Toaster />
            </OverlayProvider>
          </GSAPProvider>
        </Theme>
        </QueryProvider>
      </body>
    </html>
  );
}
